#!/bin/sh
#
# Copyright (C) 2016 The EFIDroid Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ARCH="$1"
CC="$2"
OUT_DIR="$3"
CFLAGS="$4"

# create out dir
mkdir -p $OUT_DIR

# generate eabi header
echo "#include <sys/syscall.h>" | "$CC" ${CFLAGS} - -E -dM | \
grep "define SYS" | cut -f2 -d" " \
| ( echo "#define DEF_SYSCALL(NAME) {#NAME, SYS_ ## NAME}," ; \
sed 's/SYS_//;s/\(.*\)/DEF_SYSCALL(&)/' ; echo "{NULL, -1}") \
| "$CC" ${CFLAGS} - -E  | ( echo "#include <sys/syscall.h>" ; cat ) \
| grep -v '# '| "$CC" ${CFLAGS} -E -P - | grep '{.*' \
> "$OUT_DIR/syscall_$ARCH.h"

# generate def header
echo "#include <sys/syscall.h>" | "$CC" ${CFLAGS} - -E -dM \
| grep "define SYS" | cut -f2 -d" " | \
sed 's/SYS_//;s/\(.*\)/DEF_SYSCALL(&)/' > "$OUT_DIR/def_syscalls.h"
