#!/usr/bin/env python

import sys
import fileinput

def gettag(line, name):
    return line[line.index(name)+len(name):].split(' ')[0].strip()

def main(argv):
    for line in fileinput.input():
        scontext = gettag(line, 'scontext=').split(':')[2]
        tcontext = gettag(line, 'tcontext=').split(':')[2]
        tclass = gettag(line, 'tclass=')
        perm = gettag(line, 'avc:  denied  { ')
        print('util_sepolicy_inject("%s", "%s", "%s", "%s");' % (scontext, tcontext, tclass, perm))
        

if __name__ == "__main__":
    try:
        main(sys.argv[1:])
    except:
        print('Error: %s' % sys.exc_info()[1])
        raise
