#!/usr/bin/env python
#
# Copyright (C) 2016 The EFIDroid Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import sys
import fileinput

def gettag(line, name):
    return line[line.index(name)+len(name):].split(' ')[0].strip()

def main(argv):
    for line in fileinput.input():
        scontext = gettag(line, 'scontext=').split(':')[2]
        tcontext = gettag(line, 'tcontext=').split(':')[2]
        tclass = gettag(line, 'tclass=')
        perm = gettag(line, '{ ')
        print('sepolicy_inject_add_rule(handle, "%s", "%s", "%s", "%s");' % (scontext, tcontext, tclass, perm))
        

if __name__ == "__main__":
    try:
        main(sys.argv[1:])
    except:
        print('Error: %s' % sys.exc_info()[1])
        raise
