#!/usr/bin/python -B

# common imports
import os.path
import sys
import glob
import os
import subprocess
import os
import re
from sys import stdin
from shutil import copyfile

# compatibility imports
try:
    from StringIO import StringIO
except ImportError:
    from io import StringIO

try:
    import ConfigParser
except ImportError:
    import configparser as ConfigParser

# color codes
txtblk='\033[0;30m' # Black - Regular
txtred='\033[0;31m' # Red
txtgrn='\033[0;32m' # Green
txtylw='\033[0;33m' # Yellow
txtblu='\033[0;34m' # Blue
txtpur='\033[0;35m' # Purple
txtcyn='\033[0;36m' # Cyan
txtwht='\033[0;37m' # White
bldblk='\033[1;30m' # Black - Bold
bldred='\033[1;31m' # Red
bldgrn='\033[1;32m' # Green
bldylw='\033[1;33m' # Yellow
bldblu='\033[1;34m' # Blue
bldpur='\033[1;35m' # Purple
bldcyn='\033[1;36m' # Cyan
bldwht='\033[1;37m' # White
unkblk='\033[4;30m' # Black - Underline
undred='\033[4;31m' # Red
undgrn='\033[4;32m' # Green
undylw='\033[4;33m' # Yellow
undblu='\033[4;34m' # Blue
undpur='\033[4;35m' # Purple
undcyn='\033[4;36m' # Cyan
undwht='\033[4;37m' # White
bakblk='\033[40m'   # Black - Background
bakred='\033[41m'   # Red
bakgrn='\033[42m'   # Green
bakylw='\033[43m'   # Yellow
bakblu='\033[44m'   # Blue
bakpur='\033[45m'   # Purple
bakcyn='\033[46m'   # Cyan
bakwht='\033[47m'   # White
txtrst='\033[0m'    # Text Reset

def pr_error(*args):
    print(bldred+" ".join(map(str,args))+txtrst)
def pr_info(*args):
    print(bldwht+" ".join(map(str,args))+txtrst)
def pr_warning(*args):
    print(bldylw+" ".join(map(str,args))+txtrst)
def pr_notice(*args):
    print(bldcyn+" ".join(map(str,args))+txtrst)
def pr_alert(*args):
    print(bldgrn+" ".join(map(str,args))+txtrst)

OUT = 'out/tmp/'
UNPACKBOOTIMG = 'out/host/mkbootimg/unpackbootimg'
BOOTIMGPREFIX = None

def inputex(msg):
    return input(bldylw+msg+txtrst)

def file2str(filename):
    data = None
    with open(filename, 'r') as f:
        data=f.read().replace('\n', '')

    return data

def getbootimgarg(name):
    global BOOTIMGPREFIX
    data = None
    with open(BOOTIMGPREFIX+name, 'r') as f:
        data=f.read().replace('\n', '')

    return data

def main(argv):
    global BOOTIMGPREFIX

    # check arguments
    if not len(argv) == 1:
        raise Exception('Invalid number of arguments')

    bootimg = argv[0]
    if not os.path.isfile(bootimg):
        raise Exception('Can\'t find '+bootimg)

    # build mkbootimg
    if not os.path.isfile(UNPACKBOOTIMG):
        subprocess.call(["make", "host_mkbootimg"])
        if not os.path.isfile(UNPACKBOOTIMG):
            raise Exception('can\'t find unpackbootimg')

    # get devicename
    devicename = inputex('Device name (vendor/codename): ')
    tmp = devicename.split('/')
    if len(tmp) != 2:
        raise Exception('Invalid device name: '+devicename)

    # get device description
    devicedesc = inputex('Device Description (i.e. Moto E): ')

    lcd_density = inputex('LCD Density: ')

    # get available targets
    targets = []
    for filename in os.listdir('bootloader/lk/common/LA.BF64/project'):
        if not re.match('msm.*\.mk|mdm.*\.mk', filename):
            continue
        name = os.path.basename(filename)
        name = os.path.splitext(name)[0]
        targets.append(name)

    # print available targets
    pr_warning('Available targets:')
    for i in range(0, len(targets)):
        target = targets[i]
        part = targets[i:]
        while len(part)<4:
            part.append('')
        print("{: >24} {: >24} {: >24} {: >24}".format(*part))

    # get target
    lktarget = None
    while not lktarget in targets:
        lktarget = inputex('LK Target: ')
        if not lktarget in targets:
            pr_error(lktarget+' is not a valid target')

    # create out directory
    try:
        os.makedirs(OUT)
    except:
        pass

    # create devicedir directory
    devicedir = 'device/'+devicename;
    try:
        os.makedirs(devicedir)
    except:
        pass

    # unpack boot image
    subprocess.call([UNPACKBOOTIMG, '-i', bootimg, '-o', OUT], stdout=subprocess.PIPE)
    
    BOOTIMGPREFIX = OUT+'/'+os.path.basename(bootimg)+'-'

    # create configparser
    config = ConfigParser.RawConfigParser(allow_no_value=True)
    config.optionxform = str
    config.add_section('variables')

    config.set('variables', 'DEVICE_NAME', devicedesc);
    config.set('variables', 'LK_TARGET', lktarget);
    config.set('variables', 'LK_BASE', "0x%08x" % (int(getbootimgarg('base'), 16)+0x8000));
    config.set('variables', 'BOOTIMG_BASE', '0x'+getbootimgarg('base'));
    config.set('variables', 'BOOTIMG_PAGESIZE', getbootimgarg('pagesize'));
    config.set('variables', 'BOOTIMG_ADDITIONAL_ARGS', '--ramdisk_offset 0x'+getbootimgarg('ramdisk_offset')+' --tags_offset 0x'+getbootimgarg('tags_offset'));
    config.set('variables', 'LCD_DENSITY', lcd_density);

    if os.path.getsize(BOOTIMGPREFIX+'dt')>0:
        copyfile(BOOTIMGPREFIX+'dt', devicedir+'/dt.img')
        config.set('variables', 'BOOTIMG_DT', '$(DEVICE_DIR)/dt.img');

    # write config
    with open(devicedir+'/config.ini', 'w') as configfile:
        config.write(configfile)

    copyfile('build/tools/fstab.multiboot_template', devicedir+'/fstab.multiboot')
    copyfile('build/tools/lk_inc.template.mk', devicedir+'/lk_inc.mk')
    

if __name__ == "__main__":
    try:
        main(sys.argv[1:])
    except:
        pr_error('Error: %s' % sys.exc_info()[1])
        raise
