#!/bin/bash
#
# Copyright (C) 2016 The EFIDroid Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

DTSOUT="$1"
DTBPATCHOUT="$TOP/out/target/$DEVICEID/lk_kernel/dtbpatched_out"
if [ -f "$DTBPATCHOUT" ];then
    DTBPATCHOUT="$TOP/out/target/$DEVICEID/lk_kernel/fdtpatched_out"
fi

set -e

if [ -z "$1" ];then
    echo "Usage: diffatags live.dts [dtbpatched_out]"
    exit 1
fi

if [ -n "$2" ];then
    DTBPATCHOUT="$2"
fi

# dump dtb from device, decompile to dts
fastbootwrapper oem dump-atags | dtc -I dtb -O dts -o "$DTSOUT"

# get socinfo from the device's dtb
socinfo=$(cat "$DTSOUT" | grep "efidroid-soc-info")

# decompile all of the patched dtb's
"$TOP/build/tools/dtb_decompall" "$DTBPATCHOUT" > /dev/null

# copy base dtb
grep -lR "$socinfo" "$DTBPATCHOUT/"*.dts | xargs -I {} cp {} "$DTSOUT.base"
