#!/usr/bin/env python
#
# Copyright (C) 2016 The EFIDroid Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# common imports
import sys
import os
import struct
import time
import subprocess

sys.path.append(os.path.join(os.path.dirname(__file__), '../core'))
from utils import *

def ROUNDUP(number, alignment):
    return (((number) + ((alignment)-1)) & ~((alignment)-1));

def getEFIDroidReleaseVersionString(version):
    s = '';
    ver_0 = ((version&0xff000000)>>24);
    ver_1 = ((version&0x00ff0000)>>16);
    ver_2 = ((version&0x0000ff00)>>8);
    ver_3 = ((version&0x000000ff));

    if ver_3>0:
        s = '.'+str(ver_3) + s;
    if ver_2>0 or len(s)>0:
        s = '.'+str(ver_2) + s;

    s = '.'+str(ver_1) + s;
    s = str(ver_0) + s;

    return s;

def main(argv):
    # check arguments
    if not len(argv) == 1:
        raise Exception('Invalid number of arguments')

    filename = argv[0]

    # oepn file
    f = open(filename, 'rb')

    # read header
    fmt = '<ccccccccLLLLLLLLL'
    fmtsz = struct.calcsize(fmt)
    header = f.read(fmtsz)
    data = struct.unpack(fmt, header[0:fmtsz])
    magic = ''.join(data[0:8])

    # check magic
    if magic != 'ANDROID!':
        raise Exception('Invalid boot image')

    kernel_size = data[8]
    kernel_addr = data[9]

    ramdisk_size = data[10]
    ramdisk_addr = data[11]

    second_size = data[12]
    second_addr = data[13]

    tags_addr = data[14]
    page_size = data[15]
    dt_size = data[16]

    # calculate offsets
    off_kernel  = page_size;
    off_ramdisk = off_kernel  + ROUNDUP(kernel_size,  page_size);
    off_second  = off_ramdisk + ROUNDUP(ramdisk_size, page_size);
    off_tags    = off_second  + ROUNDUP(second_size,  page_size);
    off_meta    = off_tags    + dt_size

    # read EFIDroid header
    f.seek(off_meta)
    fmt = '<ccccccccLLLLLLLL'
    fmtsz = struct.calcsize(fmt)
    header = f.read(fmtsz)
    data = struct.unpack(fmt, header[0:fmtsz])
    magic = ''.join(data[0:8])
    print(data)

    # check magic
    if magic != 'EFIDroid':
        raise Exception('Invalid metadata')

    # parse data
    ff_version = data[8]
    timestamp = data[9]
    efispec_version = data[10]
    efidroid_version = data[11]
    devicename_size = data[12]
    devicename_off = data[13]
    manifest_size = data[14]
    manifest_off = data[15]

    print('Metadata version: %u' % (ff_version))
    print('EFIDroid version: %s' % getEFIDroidReleaseVersionString(efidroid_version))
    print('Build time: %s' % (time.ctime(timestamp)))
    print('EFI Specification: %u.%u' % ((efispec_version>>16)&0xffff, efispec_version&0xffff))

    # get devicename
    f.seek(off_meta+devicename_off)
    devicename = f.read(devicename_size)
    print('Device: %s' % (devicename))

    # get manifest
    f.seek(off_meta+manifest_off)
    manifest = f.read(manifest_size)
    print('')
    print('========== Manifest ==========')
    print(manifest)
    
    f.close()

if __name__ == '__main__':
    try:
        main(sys.argv[1:])
    except:
        pr_error('Error: %s' % sys.exc_info()[1])
        raise
