#!/bin/bash
#
# Copyright (C) 2016 The EFIDroid Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

export SOURCE="$1"
export BUILD="$2"

set -e

GREP_EXCLUDES='.git$\|.gitignore$\|Conf$\|BaseTools$'

# delete old links
find ${BUILD} -maxdepth 1 -type l | grep -v ${GREP_EXCLUDES} | xargs -I{} rm {}

# create links
find ${SOURCE} -maxdepth 1 | grep -v ${GREP_EXCLUDES} | xargs -I{} sh -c 'ln -s {} ${BUILD}/$(basename {})'

# copy BaseTools
mkdir -p ${BUILD}/BaseTools
cp -Rp ${SOURCE}/BaseTools/* ${BUILD}/BaseTools/

# copy Conf
mkdir -p ${BUILD}/Conf
cp -Rp ${SOURCE}/Conf/* ${BUILD}/Conf/

# symlink our packages
for d in ${PWD}/uefi/edk2packages/*; do
	ln -s ${d} ${BUILD}/${d##*/}
done
