#!/bin/bash

export SOURCE="$1"
export BUILD="$2"

set -e

GREP_EXCLUDES='.git$\|.gitignore$\|Conf$\|BaseTools$'

# delete old links
find ${BUILD} -maxdepth 1 -type l | grep -v ${GREP_EXCLUDES} | xargs -I{} rm {}

# create links
find ${SOURCE} -maxdepth 1 | grep -v ${GREP_EXCLUDES} | xargs -I{} sh -c 'ln -s {} ${BUILD}/$(basename {})'

# copy BaseTools
mkdir -p ${BUILD}/BaseTools
cp -Rp ${SOURCE}/BaseTools/* ${BUILD}/BaseTools/

# copy Conf
mkdir -p ${BUILD}/Conf
cp -Rp ${SOURCE}/Conf/* ${BUILD}/Conf/

# symlink our packages
for d in ${PWD}/uefi/edk2packages/*; do
	ln -s ${d} ${BUILD}/${d##*/}
done
