#!/usr/bin/python -B

import sys
import subprocess

bldylw='\033[1;33m' # Yellow
txtrst='\033[0m'    # Text Reset

def inputex(msg):
    prompt = msg

    try:
        return raw_input(prompt)
    except:
        return input(prompt)

def fastboot(argv, rawmode, suppressstatus=False):
    p = subprocess.Popen(['fastboot'] + argv, stderr=subprocess.PIPE)

    first = True
    for line in p.stderr:
        line = line.decode()

        if first and line.startswith('...'):
            first = False
            continue

        if line.startswith('(bootloader) '):
            line = line[13:]
        elif rawmode:
            print()

        if suppressstatus:
            if line.startswith('OKAY ['):
                continue
            if line.startswith('finished. total time: '):
                continue

        if rawmode:
            line = line[:-1]

        sys.stdout.write(line)

def run_shell():
    while True:
        cmd = inputex(bldylw+'Shell> '+txtrst);
        fastboot(['oem', 'shell', cmd], True, True)

def main(argv):
    rawmode = False
    if len(argv)>=2 and argv[0]=='oem':
        if argv[1]=='last_kmsg':
            rawmode = True
        elif argv[1]=='lk_log':
            rawmode = True
        elif argv[1]=='shell':
            return run_shell()

    fastboot(argv, rawmode)

if __name__ == '__main__':
    try:
        main(sys.argv[1:])
    except:
        print('Error: %s' % sys.exc_info()[1])
        raise
