#!/bin/bash
#
# Copyright (C) 2016 The EFIDroid Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#set -e
#set -x

RANGEOTHER="$1"
RANGETHIS="$2"
TMPFILE="/tmp/getmissingcommits_out.txt"

# get list of commits
git log --oneline --no-merges "$RANGEOTHER" > "$TMPFILE"

while read line; do
    #echo "Checking: $line"
	commitmsg=$(echo $line | cut -d' ' -f2-)
	matchcount="$(git log --oneline --no-merges "$RANGETHIS" | grep -cF "${commitmsg}")"

	if [ $matchcount -eq 0 ];then
		echo "$line"
	fi
done < "$TMPFILE"
