#!/usr/bin/python

import uuid

guid = uuid.uuid4()

print("1:", guid);
print("2:", str(guid).upper());


bguid = guid.bytes
# { 0xc2217e7d, 0x6853, 0x4c3f, { 0xae, 0x97, 0xaf, 0xbc, 0x85, 0xc9, 0xa1, 0xe0 }}
print(
    "3: { 0x%02x%02x%02x%02x, 0x%02x%02x, 0x%02x%02x, { 0x%02x, 0x%02x, 0x%02x, 0x%02x, 0x%02x, 0x%02x, 0x%02x, 0x%02x }}" 
    % (
        bguid[0],
        bguid[1],
        bguid[2],
        bguid[3],
        bguid[4],
        bguid[5],
        bguid[6],
        bguid[7],
        bguid[8],
        bguid[9],
        bguid[10],
        bguid[11],
        bguid[12],
        bguid[13],
        bguid[14],
        bguid[15],
    )
);

print(
    "4: { 0x%02x, 0x%02x, 0x%02x, 0x%02x, 0x%02x, 0x%02x, 0x%02x, 0x%02x, 0x%02x, 0x%02x, 0x%02x, 0x%02x, 0x%02x, 0x%02x, 0x%02x, 0x%02x }" 
    % (
        bguid[0],
        bguid[1],
        bguid[2],
        bguid[3],
        bguid[4],
        bguid[5],
        bguid[6],
        bguid[7],
        bguid[8],
        bguid[9],
        bguid[10],
        bguid[11],
        bguid[12],
        bguid[13],
        bguid[14],
        bguid[15],
    )
);
