#!/usr/bin/env python
import re, os, sys, argparse, multiprocessing, fnmatch
from shutil import copyfile

srctree = ""

headers = set()
includes = set()
redefines = set()

def relpath2abspath(relpath):
    return srctree + "/" + relpath

def find_symbols(regexp, store):
    for h in headers:
        f = open(h)
        for l in f.readlines():
            m = regexp.search(l)
            if not m:
                continue
            for e in reversed(m.groups()):
                if e:
                    store.add(e)
                    break
        f.close()

def find_ml_symbols(regexp, store):
    for h in headers:
        for i in regexp.finditer(open(h).read()):
            for j in reversed(i.groups()):
                if j:
                    store.add(j)
                    break

def find_enums(block_regexp, symbol_regexp, store):
    for h in headers:
        # remove comments
        content = re.sub(re.compile("(\/\*(\*(?!\/)|[^*])*\*\/)", re.S|re.M), " ", open(h).read())
        # remove preprocesor lines
        clean_content = ""
        for l in content.split("\n"):
            if re.match("\s*#", l):
                continue
            clean_content += l + "\n"
        for i in block_regexp.finditer(clean_content):
            for j in reversed(i.groups()):
                if j:
                    for k in symbol_regexp.finditer(j):
                        for l in k.groups():
                            if l:
                                store.add(l)
                                break

def lkl_prefix(w):
    r = ""

    if w.startswith("__"):
        r = "__"
    elif w.startswith("_"):
        r = "_"

    if w.isupper():
        r += args.prefix.upper()
    else:
        r += args.prefix.lower()

    if not w.startswith("_"):
        r += "_"

    r += w

    return r

def replace(h):
    content = open(h).read()
    for i in includes:
        search_str = "(#[ \t]*include[ \t]*[<\"][ \t]*)" + i + "([ \t]*[>\"])"
        replace_str = "\\1" + args.subdir+"/" + i + "\\2"
        content = re.sub(search_str, replace_str, content)

    if False:
        tmp = ""
        for w in re.split("(\W+)", content):
            if w in defines:
                w = lkl_prefix(w)
            tmp += w
        content = tmp
        for s in structs:
            search_str = "(\W?struct\s+)" + s + "(\W)"
            replace_str = "\\1" + lkl_prefix(s) + "\\2"
            content = re.sub(search_str, replace_str, content, flags = re.MULTILINE)
        for s in unions:
            search_str = "(\W?union\s+)" + s + "(\W)"
            replace_str = "\\1" + lkl_prefix(s) + "\\2"
            content = re.sub(search_str, replace_str, content, flags = re.MULTILINE)
    for r in redefines:
        search_str = "([ \t\(*])" + r[0]
        replace_str = "\\1" + r[1]
        content = re.sub(search_str, replace_str, content)
    open(h, 'w').write(content)

parser = argparse.ArgumentParser(description='install headers')
parser.add_argument('srcdir', help='path to copy headers from', )
parser.add_argument('path', help='path to install to', )
parser.add_argument('-r', '--rename', help='rename symbols', type=argparse.FileType('rU'))
parser.add_argument('-s', '--subdir', help='move headers to subdirectory', default='', type=str)
parser.add_argument('-p', '--prefix', help='use prefix for types and functions', default='', type=str)
parser.add_argument('-j', '--jobs', help='number of parallel jobs', default=1, type=int)
args = parser.parse_args()
srctree = args.srcdir

if args.rename:
    for line in args.rename:
        parts = line.split()

        if parts[0]=='value':
            continue

        redefines.add((parts[0],parts[1]))

for root, dirnames, filenames in os.walk(srctree):
    relroot = root[len(srctree):]

    for filename in filenames:
        headers.add(os.path.join(relroot, filename))
        includes.add(os.path.join(relroot, filename))

new_headers = set()

for h in headers:
    dir = os.path.dirname(h)
    copyfromdir = os.path.dirname(relpath2abspath(h))
    out_dir = args.path + '/'+args.subdir+'/' + dir
    try:
        os.makedirs(out_dir)
    except:
        pass
    print("  INSTALL\t%s" % (out_dir + "/" + os.path.basename(h)))
    copyfile(copyfromdir+"/"+os.path.basename(h), out_dir+"/"+os.path.basename(h));
    new_headers.add(out_dir + "/" + os.path.basename(h))

headers = new_headers

defines = set()
structs = set()
unions = set()

p = re.compile("#[ \t]*define[ \t]*(\w+)")
find_symbols(p, defines)
p = re.compile("typedef.*(\(\*(\w+)\)\(.*\)\s*|\W+(\w+)\s*|\s+(\w+)\(.*\)\s*);")
find_symbols(p, defines)
p = re.compile("typedef\s+(struct|union)\s+\w*\s*{[^\\{\}]*}\W*(\w+)\s*;", re.M|re.S)
find_ml_symbols(p, defines)
defines.add("siginfo_t")
defines.add("sigevent_t")
p = re.compile("struct\s+(\w+)\s*\{")
find_symbols(p, structs)
structs.add("iovec")
p = re.compile("union\s+(\w+)\s*\{")
find_symbols(p, unions)
p = re.compile("static\s+__inline__(\s+\w+)+\s+(\w+)\([^)]*\)\s")
find_symbols(p, defines)
p = re.compile("enum\s+(\w*)\s*{([^}]*)}", re.M|re.S)
q = re.compile("(\w+)\s*(,|=[^,]*|$)", re.M|re.S)
find_enums(p, q, defines)

def process_header(h):
    print("  REPLACE\t%s" % (out_dir + "/" + os.path.basename(h)))
    replace(h)

p = multiprocessing.Pool(args.jobs)
try:
    p.map_async(process_header, headers).wait(999999)
    p.close()
except:
    p.terminate()
finally:
    p.join()
