#!/bin/bash
#
# Copyright (C) 2016 The EFIDroid Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

OUTDIR="$1"
CONFIGINC="$2"
SCRIPT="$3"
MODULE_TYPE="$4"
MODULE_NAME="$5"
MODULE_OUT="$6"
MODULE_DIR="$7"
COMPILEFN="$8"

mkdir -p "$MODULE_OUT"

FEXT="${SCRIPT##*.}"
if [ "$FEXT" == "sh" ];then
    "$EFIDROID_SHELL" -c "set -e && \
                 source \"$CONFIGINC.sh\" && \
                 source \"\$OUT/buildtime_variables.sh\" && \
                 source \"\$TOP/build/core/compilescript_inc.sh\" && \
                 export MODULE_TYPE=\"$MODULE_TYPE\" && \
                 export MODULE_OUT=\"$MODULE_OUT\" && \
                 export MODULE_NAME=\"$MODULE_NAME\" && \
                 export MODULE_DIR=\"$MODULE_DIR\" && \
                 source \"$SCRIPT\" && \
                 \"$COMPILEFN\" \
                "
elif [ "$FEXT" == "py" ];then
    python -c "execfile(\"$CONFIGINC.py\");\
               execfile(OUT+\"/buildtime_variables.py\");\
               execfile(TOP+\"/build/core/compilescript_inc.py\");\
               globals()['MODULE_TYPE'] = '$MODULE_TYPE'; \
               globals()['MODULE_OUT'] = '$MODULE_OUT'; \
               globals()['MODULE_NAME'] = '$MODULE_NAME'; \
               globals()['MODULE_DIR'] = '$MODULE_DIR'; \
               execfile(\"$SCRIPT\");\
               $COMPILEFN();
              "
else
    echo "Invalid file extension"
    exit 1
fi
