#!/bin/bash
#
# Copyright (C) 2016 The EFIDroid Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# get arguments
SERVER_PORT="$1"
if [ "$SERVER_PORT" == "" ];then
    echo "Usage: start_localserver PORT"
    exit 1    
fi
if [ "$TOP" == "" ];then
    echo "You need to run envsetup first"
    exit 1
fi
SERVER_ROOT="$TOP/out/serverroot"

# cleanup
rm -Rf "$SERVER_ROOT"

# create root dir
mkdir -p "$SERVER_ROOT"

# ota
mkdir "$SERVER_ROOT/ota"
ln -s "$TOP/ota" "$SERVER_ROOT/ota/master"

# device
ln -s "$TOP/device" "$SERVER_ROOT/device"

# build dir
ln -s "$TOP/out/target" "$SERVER_ROOT/builds"

# start server
cd "$SERVER_ROOT"
python -m SimpleHTTPServer "$SERVER_PORT"
